# Generated by Django 4.0.7 on 2022-08-07 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Noticia', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticia',
            name='titulo_cartel',
            field=models.CharField(default='pagina de noticias', max_length=255),
        ),
    ]
