# Generated by Django 4.0.7 on 2022-08-08 06:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Noticia', '0002_noticia_titulo_cartel'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticia',
            name='fecha_noticia',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='noticia',
            name='titulo_cartel',
            field=models.CharField(max_length=255),
        ),
    ]
