# Generated by Django 4.0.7 on 2022-08-18 00:02

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Noticia', '0003_noticia_fecha_noticia_alter_noticia_titulo_cartel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='cuerpo',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
