# Generated by Django 4.0.7 on 2022-08-20 00:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Noticia', '0004_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='noticia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='Noticia.noticia'),
        ),
    ]
