# Generated by Django 4.0.7 on 2022-08-24 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Noticia', '0007_alter_noticia_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='categoria',
            field=models.CharField(choices=[('Cursos', 'Cursos'), ('Informacion', 'Informacion'), ('Ingresos', 'Ingresos'), ('Ambiental', 'Ambiental'), ('Deportes', 'Deportes')], default=1, max_length=255),
        ),
    ]
