# Generated by Django 3.0 on 2022-08-06 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Inicio',
        ),
    ]
