# Generated by Django 3.0 on 2022-08-06 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0003_inicio'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Inicio',
        ),
    ]
