# Generated by Django 4.0.7 on 2022-08-20 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('usuario', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20)),
                ('apellido', models.CharField(max_length=20)),
                ('mail', models.CharField(max_length=50)),
                ('contraseña', models.CharField(max_length=16)),
                ('es_administrador', models.BooleanField(default=False)),
            ],
        ),
    ]
