# Generated by Django 4.0.7 on 2022-08-21 00:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Visitante', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
